export const AUDIT_JOB_NAMES = {
  CLEANUP_OLD_LOGS: 'cleanup-old-logs',
} as const;

export const AUDIT_SYSTEM_SETTING_KEYS = {
  CLEANUP_RETENTION_DAYS: 'AUDIT_CLEANUP_RETENTION_DAYS',
} as const;

export const AUDIT_ACTION_CODES = {
  CLEANUP_EXECUTED: 'AUDIT_CLEANUP_EXECUTED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_ANOMALY: 'LOGIN_ANOMALY',
  FILE_UPLOAD: 'FILE_UPLOAD',
  FILE_EDIT: 'FILE_EDIT',
  FILE_DELETE_REQUEST: 'FILE_DELETE_REQUEST',
  FILE_ARCHIVE: 'FILE_ARCHIVE',
  CONTENT_DISABLE: 'CONTENT_DISABLE',
  FILE_DELETE: 'FILE_DELETE',
} as const;

export const AUDIT_ENTITY_TYPES = {
  SYSTEM: 'SYSTEM',
  MATERIAL: 'material',
  FOLDER: 'folder',
  USER: 'user',
  ENROLLMENT: 'enrollment',
  EVALUATION: 'evaluation',
  COURSE: 'course',
} as const;

export const AUDIT_SYSTEM_ACTOR = {
  USER_ID: '1',
} as const;
