export const MEDIA_CONTENT_KINDS = {
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
} as const;

export const MEDIA_ACCESS_MODES = {
  DIRECT_URL: 'DIRECT_URL',
  BACKEND_PROXY: 'BACKEND_PROXY',
} as const;

export const MEDIA_ACCESS_MEMBERSHIP_ACTIONS = {
  GRANT: 'GRANT',
  REVOKE: 'REVOKE',
} as const;

export const MEDIA_ACCESS_JOB_NAMES = {
  SYNC_MEMBERSHIP: 'SYNC_MEMBERSHIP',
  RECONCILE_SCOPES: 'RECONCILE_SCOPES',
} as const;

export const MEDIA_ACCESS_SYNC_SOURCES = {
  ENROLLMENT_CREATED: 'ENROLLMENT_CREATED',
  ENROLLMENT_CANCELLED: 'ENROLLMENT_CANCELLED',
  EVALUATION_CREATED_BANK: 'EVALUATION_CREATED_BANK',
  EVALUATION_CREATED_FULL: 'EVALUATION_CREATED_FULL',
  RECONCILIATION: 'RECONCILIATION',
} as const;

export type MediaContentKind =
  (typeof MEDIA_CONTENT_KINDS)[keyof typeof MEDIA_CONTENT_KINDS];
export type MediaAccessMode =
  (typeof MEDIA_ACCESS_MODES)[keyof typeof MEDIA_ACCESS_MODES];
export type MediaAccessMembershipAction =
  (typeof MEDIA_ACCESS_MEMBERSHIP_ACTIONS)[keyof typeof MEDIA_ACCESS_MEMBERSHIP_ACTIONS];
