export type AnomalyType =
  | 'NONE'
  | 'IMPOSSIBLE_TRAVEL'
  | 'NEW_DEVICE_QUICK_CHANGE';

export const ANOMALY_TYPES: Record<string, AnomalyType> = {
  NONE: 'NONE',
  IMPOSSIBLE_TRAVEL: 'IMPOSSIBLE_TRAVEL',
  NEW_DEVICE_QUICK_CHANGE: 'NEW_DEVICE_QUICK_CHANGE',
};

export type ConcurrentDecision = 'KEEP_NEW' | 'KEEP_EXISTING';

export const CONCURRENT_DECISIONS: Record<string, ConcurrentDecision> = {
  KEEP_NEW: 'KEEP_NEW',
  KEEP_EXISTING: 'KEEP_EXISTING',
};

export type IdentitySourceFlow =
  | 'LOGIN_GOOGLE'
  | 'ANOMALOUS_REAUTH'
  | 'REFRESH_TOKEN'
  | 'CONCURRENT_RESOLUTION';

export const IDENTITY_SOURCE_FLOWS: Record<string, IdentitySourceFlow> = {
  LOGIN_GOOGLE: 'LOGIN_GOOGLE',
  ANOMALOUS_REAUTH: 'ANOMALOUS_REAUTH',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  CONCURRENT_RESOLUTION: 'CONCURRENT_RESOLUTION',
};

export type SecurityEventCode =
  | 'ACCESS_DENIED'
  | 'PROFILE_SWITCH'
  | 'LOGOUT_SUCCESS'
  | 'LOGIN_SUCCESS'
  | 'LOGIN_FAILED'
  | 'NEW_DEVICE_DETECTED'
  | 'CONCURRENT_SESSION_DETECTED'
  | 'CONCURRENT_SESSION_RESOLVED'
  | 'ANOMALOUS_LOGIN_DETECTED'
  | 'ANOMALOUS_LOGIN_REAUTH_FAILED'
  | 'ANOMALOUS_LOGIN_REAUTH_SUCCESS';

export const SECURITY_EVENT_CODES: Record<string, SecurityEventCode> = {
  ACCESS_DENIED: 'ACCESS_DENIED',
  PROFILE_SWITCH: 'PROFILE_SWITCH',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  NEW_DEVICE_DETECTED: 'NEW_DEVICE_DETECTED',
  CONCURRENT_SESSION_DETECTED: 'CONCURRENT_SESSION_DETECTED',
  CONCURRENT_SESSION_RESOLVED: 'CONCURRENT_SESSION_RESOLVED',
  ANOMALOUS_LOGIN_DETECTED: 'ANOMALOUS_LOGIN_DETECTED',
  ANOMALOUS_LOGIN_REAUTH_FAILED: 'ANOMALOUS_LOGIN_REAUTH_FAILED',
  ANOMALOUS_LOGIN_REAUTH_SUCCESS: 'ANOMALOUS_LOGIN_REAUTH_SUCCESS',
};

export const LOCATION_SOURCES = {
  IP: 'ip',
  GPS: 'gps',
  NONE: 'none',
} as const;

export type LocationSource =
  (typeof LOCATION_SOURCES)[keyof typeof LOCATION_SOURCES];

export const PHOTO_SOURCES = {
  GOOGLE: 'google',
  UPLOADED: 'uploaded',
  PROFILE: 'profile',
  NONE: 'none',
} as const;

export type PhotoSourceValue =
  (typeof PHOTO_SOURCES)[keyof typeof PHOTO_SOURCES];

export type IdentityDenyReason = 'INACTIVE_ACCOUNT';

export const IDENTITY_DENY_REASONS: Record<string, IdentityDenyReason> = {
  INACTIVE_ACCOUNT: 'INACTIVE_ACCOUNT',
};

export type IdentityInvalidationReason =
  | 'USER_BANNED'
  | 'SENSITIVE_UPDATE'
  | 'ROLE_CHANGE'
  | 'UNSPECIFIED';

export const IDENTITY_INVALIDATION_REASONS: Record<
  string,
  IdentityInvalidationReason
> = {
  USER_BANNED: 'USER_BANNED',
  SENSITIVE_UPDATE: 'SENSITIVE_UPDATE',
  ROLE_CHANGE: 'ROLE_CHANGE',
  UNSPECIFIED: 'UNSPECIFIED',
};

export type SessionStatusCodeValue =
  | 'ACTIVE'
  | 'PENDING_CONCURRENT_RESOLUTION'
  | 'BLOCKED_PENDING_REAUTH'
  | 'REVOKED';

export const SESSION_STATUS_CODES: Record<string, SessionStatusCodeValue> = {
  ACTIVE: 'ACTIVE',
  PENDING_CONCURRENT_RESOLUTION: 'PENDING_CONCURRENT_RESOLUTION',
  BLOCKED_PENDING_REAUTH: 'BLOCKED_PENDING_REAUTH',
  REVOKED: 'REVOKED',
};

export const SECURITY_MESSAGES = {
  INACTIVE_ACCOUNT:
    'Tu cuenta se encuentra inactiva. Contacta a administracion.',
  INVALID_SESSION: 'Sesión inválida o expirada',
  REVOKED_TOKEN: 'Token revocado',
  UNAUTHORIZED_DEVICE: 'Dispositivo no autorizado',
} as const;
